### ISSUE TITLE
[lxd] Additional items to implement/fix

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#1586]
This is a place to dump additional items to implement and/or fix in subsequent iterations.  This was started in #1533, but this will make it easier to track.

- [x] Additional test coverage. (#1574) MERGED
- [x] See if it's possible to mock `NetworkAccessManager` and `LocalSocketReply` instead of using `MockLocalSocketServer`. (#1572) MERGED
- [x] Figure out a way to use a single `NetworkAccessManager` across `LXDVirtualMachineFactory` and `LXDVMImageVault`. (#1587) MERGED
- [x] Overhaul `LXDVirtualMachineFactory::hypervisor_health_check()` including detecting if LXD socket is not available, etc. (#1574) MERGED
- [x] Determine how best to handle the cloud-init YAML config. Do we store it somewhere and re-populate upon daemon start so `VirtualMachineDesription` contains the values? Do we just create it once and let `LXDVirtualMachineFactory` configure it and then forget about it since LXD has it stored? **Answer: The current implementation does what we need.**
- [x] Re-add back in `lxd_request()` the ability to wait on operations to complete.  **Update:** Added a separate `lxd_wait()` function to allow caller to determine if it should wait or not. (#1835) MERGED
- [x] Fix `LXDVirtualMachine` to wait on an instance to be created instead of the clunky while loop w/ sleep(). (#1574) MERGED
- [x] Determine if LXD itself can properly update and prune source images and potentially refactor the `VMImageVault`'s `update_images()` and `prune_expired_images()` and associated timer. (#1594) MERGED
- [x] Determine if the source part of the LXD initialization can be modified to not explicitly call out the remote since the image should already be in the local repository. (#1682) MERGED
- [x] Allow importing images from the "custom" image host ~~and http/file based launches~~. (#1679) MERGED
- [x] Enable http & file based launches. (#1931) MERGED
- [ ] Implement a way to use websockets to subscribe to operation events.  Perhaps `QWebSockets`.
- [ ] Optimize `NetworkAccessManager` to keep an open connection to the LXD socket and close that connection after a period of time of inactivity.
- [x] ~~Implement suspend functionality.~~ Disable suspend support and throw error.  LXD currently does not support saving state of an instance. (#1604) - MERGED
- [x] Increase timeout when waiting for an instance to shut down. (#1784) MERGED
- [x] #1612 - Fix client from showing `Retrieving image: 100%` before showing the real percentage when first downloading an image. This is due to 2 downloads taking place- a `metadata` download which is quick and then a download of the actual image.  The first 100% is for the metadata.  I'm not sure if we should actually show both like `lxc launch` does. (#1612) MERGED
- [ ] Investigate why on daemon start up, it temporarily blocks client connections with `EPERM` when instances exist. **Update:** This also needs #1637 to be fixed as well. (#1599) - INPROGRESS
- [x] Fully implement `get_backend_version_string()`. (#1636) - MERGED
- [x] Use a snap refresh hook to clue the daemon that it is being restarted because of a snap refresh so as to not stop any running instances on daemon shutdown. (#1639) - MERGED
- [ ] Rework `hypervisor_health_check()` logic into an `initialize()` function that checks for prerequisites and initializes any missing prerequisites that it is able to do.  If it can't, then it throws with the appropriate exception.  In addition, the daemon will wrap calls to `initialize()` in `create`&`start` in a `try`/`catch` block, so if it fails, then it call call `factory->initialize()` and try again if it passes.
- [ ] Fail delete of instance if it's still being initialized by LXD.
- [x] Disable secure boot for all instances. (#1736) - MERGED

**Comment by townsend2010** [comment]
This is pretty much done minus the few items not completed here.  I think any new features we do for LXD should be tracked in separate issues, so closing this as complete now.
