### ISSUE TITLE
1.13 regression testing tracker

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#3325]
This is to track the regression testing of the [1.13.0 RC](https://github.com/canonical/multipass/releases/tag/v1.13.0-rc).

- [x] Linux/Qemu (@andrei-toterman )
- [x] Linux/LXD (@sharder996)
- [x] Linux/libvirt (@georgeliao)
- [x] Intel Mac/Qemu (@andrei-toterman)
- [x] Intel Mac/Virtualbox (@ricab)
- [x] Arm Mac/Qemu (@sharder996)
- [x] Windows/Hyper-V (@georgeliao)
- [x] Windows/Virtualbox ~~(@ricab)~~(@luis4a0)

**Comment by sharder996** [comment]
@townsend2010

Found a regression with `multipass find` on macOS with how returned images are filtered. In the RC package, there are two issues that I see:
1. A snapcraft/core24 image is showing up when they are not supported
2. The `mantic` image is not showing up

**Comment by andrei-toterman** [comment]
The release notes say that we only support macOS 11 or newer. I think we should update the installer message with that.
<img width="732" alt="Screenshot 2023-12-11 at 13 24 36" src="https://github.com/canonical/multipass/assets/18419918/305fbd8a-7ffe-41cf-9bd1-f56dbc99a4a6">
Also, since we did that change of removing years from copyright statements, should we remove it here too?
<img width="732" alt="Screenshot 2023-12-11 at 13 25 47" src="https://github.com/canonical/multipass/assets/18419918/a7515395-0564-4c2e-bc11-c6e1f9ae4587">

**Comment by georgeliao** [comment]
I can confirm the two issues @sharder996 found, they only occur on windows and macos, not on linux. 

> A snapcraft/core24 image is showing up when they are not supported
> The mantic image is not showing up

**Comment by townsend2010** [comment]
Hey @sharder996 & @georgeliao,

We always support `snapcraft:devel` which is `snapcraft:core24` right now, so it is indeed support.  I do need to fix the lack of `mantic` though.

**Comment by sharder996** [comment]
@townsend2010 

> We always support snapcraft:devel which is snapcraft:core24 right now, so it is indeed support.

There is still a disparity since the image doesn't show up in 1.12.2 Is this something that we meant to change?

**Comment by sharder996** [comment]
@townsend2010 @andrei-toterman 

Looks like the copyright year still exists in the Windows installer as well.

**Comment by townsend2010** [comment]
Hey @sharder996,

> Is this something that we meant to change?

Yes, it was "broken" before in that we had to update the supported releases filter when we released a new version of Multipass.  But this was fixed in #3072 and we no longer have to add or remove anything for the `snapcraft` remote.

**Comment by townsend2010** [comment]
After a bit more investigation, the `snapcraft:core24` showing up for `multipass find` on Windows and macOS is not correct.  That is #3274 and I will need to fix that for a better user experience in this case.

**Comment by townsend2010** [comment]
We've released 1.13.0, so closing this.
